# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
# Text to speech
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensor.yaml
frontend:
  themes: !include_dir_merge_named themes/
  extra_module_url:
    - /local/card-mod.js

http:
  server_port: 8123
  use_x_forwarded_for: true
  trusted_proxies:
    - !secret Proxy


plant: !include plants.yaml

discovery:
  ignore:
    - yamaha
    - logitech_mediaserver

lovelace:
  resources:
    - url: /hacsfiles/frigate-hass-card/frigate-hass-card.js
      type: module
    - url: /local/state-switch.js
      type: module


device_tracker:
  - platform: snmp
    host: 192.168.1.1
    community: public
    baseoid: 1.3.6.1.4.1.14988.1.1.1.2.1.1
  - platform: mojio
    domain: tmobile-us
    client_id: !secret clientid
    client_secret: !secret client_secret
    username: !secret syncupuser
    password: !secret syncuppass
  
light: 
  - platform: group
    name: Living Room 
    unique_id: “living_room2”
    entities:
      - light.living_room_light_a
      - light.living_room_light_b
      - light.living_room_light_c
      - light.living_room_lamp_2
      - light.elements_8f9c
      - light.living_room_mood_lighting
  - platform: group
    name: Bedroom Lights
    unique_id: “Bedroom_Lights_87”
    entities:
      - light.master_bedroom_lamp
      - light.master_bedroom_dab_lamp
      - light.nanoleaf
  - platform: group
    name: All Bedroom Lights
    unique_id: “All_Bedroom_Lights"
    entities:
      - light.master_bedroom_lamp
      - light.master_bedroom_dab_lamp
      - light.nanoleaf
      - light.plate01_backlight
  - platform: group
    name: Outdoor Lights
    unique_id: “All_Outdoor_Lights"
    entities:
      - light.kitchen_outdoor_light
      - light.sliding_door_outdoor_light
      - light.front_outdoor_lights
  - platform: group
    name: Upstairs Hall Lights
    unique_id: “All_Upstairs_Hall_Lights"
    entities:
      - light.entryway_lights
      - light.upstairs_hallway_lights
  - platform: group
    name: Garage Combined Lights
    unique_id: “Garage_Combined_Lights"
    entities:
      - light.garage_overhead_lamps
      - light.garage_overhead_lights
      - light.garage_lamp_light_2

#telegram Bits
telegram_bot:
  - platform: polling
    api_key: !secret telegrambot
    allowed_chat_ids:
      - !secret user  # this is a user
      - !secret group # is a group (with the "-" symbol)

notify:
  - platform: telegram
    name: HomeChat
    chat_id: !secret HomeChat
  - platform: telegram
    name: JustGoat
    chat_id: !secret Goat

    



#DB information
recorder:
  db_url: !secret mariadb
  purge_keep_days: 7

influxdb:
  host: 192.168.1.30
  port: 8086
  database: !secret influxdb2
  username: !secret influxdb3
  password: !secret influxdb
  max_retries: 3
  default_measurement: state
# Input select for Zigbee2MQTT debug level
input_select:
  zigbee2mqtt_log_level:
    name: Zigbee2MQTT Log Level
    options:
      - debug
      - info
      - warn
      - error
    initial: info
    icon: mdi:format-list-bulleted
# Input number for joining time remaining (in minutes)
input_number:
  zigbee2mqtt_join_minutes:
    name: "Zigbee2MQTT join minutes"
    initial: 2
    min: 1
    max: 5
    step: 1
    mode: slider
# Input text to input Zigbee2MQTT friendly_name for scripts
input_text:
  zigbee2mqtt_old_name:
    name: Zigbee2MQTT Old Name
    initial: ""
  zigbee2mqtt_new_name:
    name: Zigbee2MQTT New Name
    initial: ""
  zigbee2mqtt_remove:
    name: Zigbee2MQTT Remove
    initial: ""
# Input boolean to set the force remove flag for devices
input_boolean:
  zigbee2mqtt_force_remove:
    name: Zigbee2MQTT Force Remove
    initial: false
    icon: mdi:alert-remove
# Timer for joining time remaining (120 sec = 2 min)
timer:
  zigbee_permit_join:
    name: Time remaining
    duration: 120
# Switch for enabling joining



cover:
  - platform: template
    covers:
      bedroom_blinds:
        friendly_name: "Bedroom Blinds"
        unique_id: “Bedroom_Blinds1”
        open_cover:
          service: switch.turn_off
          data:
            entity_id: switch.bedroom_blinds_closed
        close_cover:
          service: switch.turn_on
          data:
            entity_id: switch.bedroom_blinds_closed
        icon_template: >-
          {% if is_state('switch.bedroom_blinds_closed', 'on') %}
            mdi:blinds-open
          {% else %}
            mdi:blinds
          {% endif %} 
  - platform: template
    covers:
      office_blinds:
        friendly_name: "Office Blinds"
        unique_id: “Office_Blinds”
        open_cover:
          service: switch.turn_off
          data:
            entity_id: switch.office_blinds_closed
        close_cover:
          service: switch.turn_on
          data:
            entity_id: switch.office_blinds_closed
        icon_template: >-
          {% if is_state('switch.office_blinds_closed', 'on') %}
            mdi:blinds-open
          {% else %}
            mdi:blinds
          {% endif %} 
  - platform: template
    covers:
      office_blinds:
        friendly_name: "Sewing Room Blinds"
        unique_id: “Sewing_Room_Blinds”
        open_cover:
          service: switch.turn_off
          data:
            entity_id: switch.sewingroom_blinds_closed
        close_cover:
          service: switch.turn_on
          data:
            entity_id: switch.sewingroom_blinds_closed
        icon_template: >-
          {% if is_state('switch.sewingroom_blinds_closed', 'on') %}
            mdi:blinds-open
          {% else %}
            mdi:blinds
          {% endif %} 
